remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Auto Insurance Claims Fraud Detection
description: Random Forest vs Neural Network Model for Auto Insurance Claims Fraud Detection
